### ISSUE TITLE
No Wire.beginTransmission and no Wire.endTransmission needed with Wire.requestFrom

### ISSUE THREAD

**Issue by Koepel** [bildr-org/6dof#1]
In the file FIMU_ADXL345.cpp and FIMU_ITG3200.cpp is a Wire.requestFrom encapsulated by Wire.beginTransmission and Wire.endTransmission. But those should only be used when writing data, they can be removed.

The Wire.requestFrom is a complete I2C transaction on its own.

**Comment by bildr-org** [comment]
Sorry. This article is about 6 years old and probably won't be updated unless it is broken. Because I personally verified every thing posted I won't make changes without verifying the changes as well - But I don't have the hardware anymore to do so.
